/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author blotcanvas
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    int close_count=0;
    static String temp;
    String name;
    mainMenu main=new mainMenu();
    public Login()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jTxtUserName = new javax.swing.JTextField();
        jButtonReset = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        jPanel1.setForeground(new java.awt.Color(204, 255, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("User Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 79, -1, -1));

        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 123, 68, -1));

        jPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 118, 130, -1));

        jTxtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtUserNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 74, 130, -1));

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jButtonLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonLoginKeyPressed(evt);
            }
        });
        jPanel1.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 280));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 176, 510, 300));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("User Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 111, -1, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Time Table Scheduling System");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 520, 50));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 67, 506, 10));

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/blotcanvas/Downloads/simple-animated-geometric-background-with-squares-4k-ultra-high-definition-video-loop_hzhlwak8x_thumbnail-full01.png")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
        if(jTxtUserName.getText().isEmpty() || jPassword.getText().isEmpty() )
        {
            JOptionPane.showMessageDialog(null,"Invalid Login Details","Login Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
        try{
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/Login_Credentials","admin_main","admin");
            java.sql.Statement stmt=con.createStatement();
            String DBQ="Select * from ADMIN_MAIN.CREDENTIALS where Username='"+jTxtUserName.getText().toUpperCase()+"' AND Password='"+jPassword.getText() +"'";
        ResultSet rs=stmt.executeQuery(DBQ);
        temp=jTxtUserName.getText();
        if(rs.next())
        {
            //JOptionPane.showMessageDialog(null, "Successful");
            jPassword.setText(null);
            jTxtUserName.setText(null);
            showName();
            JOptionPane.showMessageDialog(null,name,"Welcome!!",JOptionPane.INFORMATION_MESSAGE);
            main.setVisible(true);
            setVisible(false);
            dispose();
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "Failed");
            JOptionPane.showMessageDialog(null,"Invalid Login Details","Login Error",JOptionPane.ERROR_MESSAGE);
            jPassword.setText(null);
            jTxtUserName.setText(null);
            close_count++;
        }
        if(close_count==3)
        {
            JOptionPane.showMessageDialog(null,"You have passed the limits of trials !!","Login Error",JOptionPane.ERROR_MESSAGE);
            close_count=0;
            System.exit(0);
        }
        }catch(HeadlessException | ClassNotFoundException | SQLException e){
           System.err.println(e);
        }
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jPassword.setText(null);
        jTxtUserName.setText(null);
    }//GEN-LAST:event_jButtonResetActionPerformed

    public String sendUser(){
        String pass=temp;
        return pass;
    }
    
    public String sendName(){
       String send=name;
        return send;
    }
    
    public void showName(){
        String user;
        mainMenu obj=new mainMenu();
        user=temp.toUpperCase();
        System.out.println(user);
        try{
                Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
                java.sql.Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/Login_Credentials","admin_main","admin");
                java.sql.Statement stmt=con.createStatement();
                String DBQ="Select * from ADMIN_MAIN.credentials where USERNAME='"+user+"' ";
                ResultSet rs=stmt.executeQuery(DBQ);
                while(rs.next()){
                    name = rs.getString("NAME");
                    System.out.println(name);
                }
            }    
        catch(HeadlessException | ClassNotFoundException | SQLException e){
           System.err.println(e);
        }
        
    }
    
    private void jTxtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtUserNameActionPerformed

    private void jButtonLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonLoginKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            JOptionPane.showMessageDialog(null,"Invalid Login Details","Login Error",JOptionPane.ERROR_MESSAGE);
            main.setVisible(true);
             setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_jButtonLoginKeyPressed

    private void jPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordKeyPressed
        // TODO add your handling code here:

       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                if(jTxtUserName.getText().isEmpty() || jPassword.getText().isEmpty() )
        {
            JOptionPane.showMessageDialog(null,"Invalid Login Details","Login Error",JOptionPane.ERROR_MESSAGE);
        }
                else{
        try{
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/Login_Credentials","admin_main","admin");
            java.sql.Statement stmt=con.createStatement();
            String DBQ="Select * from ADMIN_MAIN.CREDENTIALS where Username='"+jTxtUserName.getText().toUpperCase()+"' AND Password='"+jPassword.getText() +"'";
        ResultSet rs=stmt.executeQuery(DBQ);
        temp=jTxtUserName.getText();
        if(rs.next())
        {
            //JOptionPane.showMessageDialog(null, "Successful");
            jPassword.setText(null);
            jTxtUserName.setText(null);
            showName();
            JOptionPane.showMessageDialog(null,name,"Welcome!!",JOptionPane.INFORMATION_MESSAGE);
            main.setVisible(true);
            setVisible(false);
            dispose();
        }
        else
        {
            //JOptionPane.showMessageDialog(null, "Failed");
            JOptionPane.showMessageDialog(null,"Invalid Login Details","Login Error",JOptionPane.ERROR_MESSAGE);
            jPassword.setText(null);
            jTxtUserName.setText(null);
            close_count++;
        }
        if(close_count==3)
        {
            JOptionPane.showMessageDialog(null,"You have passed the limits of trials !!","Login Error",JOptionPane.ERROR_MESSAGE);
            close_count=0;
            System.exit(0);
        }
        }catch(HeadlessException | ClassNotFoundException | SQLException e){
           System.err.println(e);
        }
       }
        }
    }//GEN-LAST:event_jPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxtUserName;
    // End of variables declaration//GEN-END:variables

    private void systemExit()
    {
        WindowEvent winClosing=new WindowEvent(this,WindowEvent.WINDOW_CLOSING); 
    }
}