/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author blotcanvas
 */
public class warning extends javax.swing.JFrame {
int flg;
teacher_selection obj=new teacher_selection();
String day;
int shift;
    /**
     * Creates new form warning
     */
    public warning() {
        initComponents();
        day=obj.sendDay();
        shift=obj.sendShift();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("WARNING!!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel2.setText("The selected slot on the selected day is already booked !");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 118, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/blotcanvas/Downloads/36d209584ab7692cbca7ff9910691a3e-abstract-gray-polygonal-background.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        flg=1;
        String teacher=null;
        teacher_selection obj=new teacher_selection();
            try{
            Login log= new Login();
            String user=log.sendUser();
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/Login_Credentials","admin_main","admin");
            java.sql.Statement stmt=con.createStatement();
            String st="select * from ADMIN_MAIN.CREDENTIALS where USERNAME='"+user+"'";
            ResultSet rs1=stmt.executeQuery(st);
            if(rs1.next())
            {
                teacher=rs1.getString("NAME");
            }
            System.out.println(teacher);
            System.out.println(day);
            System.out.println(shift);
            String st1="select * from ADMIN_MAIN.INFO1 where TEACHER='"+teacher+"'";
            ResultSet rs2=stmt.executeQuery(st1);
            PreparedStatement ps;
            int dash=0;
            if(rs2.next()){
            if("TUESDAY".equals(day) && 1==shift)
                {
                    String insert2 = "update ADMIN_MAIN.INFO1 set TU_SLOT1_TIME= "+dash+" where TEACHER='"+teacher+"'";
                    stmt.executeUpdate(insert2);   
                }
            if("TUESDAY".equals(day) && 2==shift)
                {
                    String insert2 = "update ADMIN_MAIN.INFO1 set TU_SLOT2_TIME= "+dash+" where TEACHER='"+teacher+"'";
                    stmt.executeUpdate(insert2);   
                }
            if("WEDNESDAY".equals(day) && 1==shift)
                {
                    String insert2 = "update ADMIN_MAIN.INFO1 set WE_SLOT1_TIME= "+dash+" where TEACHER='"+teacher+"'";
                    stmt.executeUpdate(insert2);   
                }
            if("WEDNESDAY".equals(day) && 2==shift)
                {
                    String insert2 = "update ADMIN_MAIN.INFO1 set WE_SLOT2_TIME= "+dash+" where TEACHER='"+teacher+"'";
                    stmt.executeUpdate(insert2);   
                }
            if("THURSDAY".equals(day) && 1==shift)
                {
                    String insert2 = "update ADMIN_MAIN.INFO1 set TH_SLOT1_TIME= "+dash+" where TEACHER='"+teacher+"'";
                    stmt.executeUpdate(insert2);   
                }
            if("THURSDAY".equals(day) && 2==shift)
                {
                    String insert2 = "update ADMIN_MAIN.INFO1 set TH_SLOT2_TIME= "+dash+" where TEACHER='"+teacher+"'";
                    stmt.executeUpdate(insert2);   
                }
            if("FRIDAY".equals(day) && 1==shift)
                {
                    String insert2 = "update ADMIN_MAIN.INFO1 set FR_SLOT1_TIME= "+dash+" where TEACHER='"+teacher+"'";
                    stmt.executeUpdate(insert2);   
                }
            if("FRIDAY".equals(day) && 2==shift)
                {
                    String insert2 = "update ADMIN_MAIN.INFO1 set FR_SLOT2_TIME= "+dash+" where TEACHER='"+teacher+"'";
                    stmt.executeUpdate(insert2);   
                }
            if("SATURDAY".equals(day) && 1==shift)
                {
                    String insert2 = "update ADMIN_MAIN.INFO1 set SA_SLOT1_TIME= "+dash+" where TEACHER='"+teacher+"'";
                    stmt.executeUpdate(insert2);   
                }
            if("SATURDAY".equals(day) && 2==shift)
                {
                    String insert2 = "update ADMIN_MAIN.INFO1 set SA_SLOT2_TIME= "+dash+" where TEACHER='"+teacher+"'";
                    stmt.executeUpdate(insert2);   
                }
            }
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e){
           System.err.println(e);
        }
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        flg=0;
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    public int sendFlg(){
        return flg;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(warning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(warning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(warning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(warning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new warning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
